#!/usr/bin/env python3
"""Replace the 85 placeholder Stone Age entries with honest, original text.

What was wrong (found 2026-09-23)
---------------------------------
Of the 102 Stone Age nodes added in September 2026, 85 carried generated
placeholder text ("A torch.", "Made by combining Hafted Tool and Fire."), the
same date for every one ("~3 million years ago" — false for a bow, a sauna or
a kiln), and a source id, 'archaeological', that does not exist in
sources.json. The validator rejects all three (E7, E10).

What this does
--------------
Writes a short original description for each: what it is (l1), why it
mattered (l2), and how anyone could know (l3). Nothing here is copied from a
source. Where a date is widely established it is given as a wide, hedged
range; everywhere else the entry says "Date not yet sourced" instead of
inventing one. Every entry is marked 'source_required' — no citation is
invented — and carries a caution that its recipe is a gameplay simplification.
`ds` stays a sort key only; it is never shown to the player.

A few display names are corrected where the placeholder name described a much
later object (a rubber "slingshot", a gunpowder "slow match", a "scythe").
Ids do not change, so saved games keep working.

Idempotent: re-running rewrites the same text.

  python3 tools/rewrite_placeholders.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILE = ROOT / "data" / "nodes" / "g8.json"

UNDATED = "Date not yet sourced"
GAMEPLAY = ("Gameplay entry. The recipe is a simplification, and the date and evidence "
            "for this entry have not yet been checked against a subject-level source.")

# id: (display name, date, ds sort key, l1, l2, l3, extra caution or "")
E: dict[str, tuple[str, str, int, str, str, str, str]] = {
    "torch": ("Torch", UNDATED, -60000,
        "Burning material carried on a stick: fire you can take with you.",
        "A torch turns fire from a place into a tool. It lights the way into caves, keeps animals back at night, and carries a flame from one hearth to start the next.",
        "Torches rarely survive, so evidence is indirect: soot marks and charcoal smears on cave walls far beyond the reach of daylight.", ""),
    "pickaxe": ("Pick", UNDATED, -8000,
        "A pointed head on a handle, swung to break ground or loosen rock.",
        "A point concentrates the whole swing on a tiny area, which is what hard ground and seamed rock need. Picks made from antler were a standard mining tool long before metal ones.",
        "Worn antler picks left behind in ancient mine shafts and pits are the usual evidence.", ""),
    "axe": ("Axe", UNDATED, -30000,
        "A heavy edge fixed to a handle and swung to cut wood.",
        "The handle turns the arm into a longer lever, so each blow lands harder than a hand-held stone could. Felling and shaping timber at scale depends on it.",
        "Stone axe heads survive well and often show polish or wear where a handle once gripped them; the handles themselves rarely survive.", ""),
    "adze": ("Adze", UNDATED, -10000,
        "Like an axe, but with the blade turned across the handle, for shaving and hollowing wood.",
        "An adze takes off thin curls instead of chopping through, which is what shaping a plank, a bowl or a canoe hull requires.",
        "Archaeologists tell adze blades from axe blades by their asymmetric edge and wear pattern.", ""),
    "hardened_spear": ("Fire-Hardened Spear", UNDATED, -300000,
        "A wooden spear whose point has been dried and toughened in a fire.",
        "Careful heating drives moisture out of the tip and makes it harder and less likely to split — a sharper weapon with no stone at all.",
        "Wooden spears are among the rarest survivals in archaeology; where they do survive, waterlogged or buried, their tips can be examined for heat treatment.", ""),
    "stone_spear": ("Stone-Tipped Spear", UNDATED, -300000,
        "A spear with a knapped stone point fixed to its tip.",
        "A stone tip cuts deeper and stays sharp longer than wood alone. Making one joins three skills at once: knapping, shaping a shaft, and fixing the two together.",
        "Stone points with damage typical of impact, and with traces of the glue or binding that held them, are the main evidence.", ""),
    "harpoon": ("Harpoon", UNDATED, -40000,
        "A barbed point that stays in its target, often tied to a line.",
        "Barbs and a line let a hunter keep hold of something in water, where a plain spear would simply come loose and be lost.",
        "Carved bone and antler points with barbs are the typical finds; how early they appear is actively debated.", ""),
    "barbed_spear": ("Barbed Spear", UNDATED, -40000,
        "A spear with backward-facing barbs cut or set into its head.",
        "Barbs make a point hard to pull back out, so a wounded animal cannot shake it free.",
        "Rows of small stone inserts set along a shaft, and carved bone points with barbs, are the usual evidence.", ""),
    "chisel": ("Chisel", UNDATED, -10000,
        "A narrow edge driven by a hammer to cut grooves and joints.",
        "Striking the tool instead of swinging it gives precise, controlled cuts — the basis of joinery and carving.",
        "Chisels are identified by their shape and by the tool marks they leave on worked wood, bone and antler.", ""),
    "bolas": ("Bolas", UNDATED, -20000,
        "Weights joined by cords, thrown to tangle an animal's legs.",
        "A bolas does not need to hit a vital spot; it only has to wrap around something moving. It is a way of catching fast animals alive.",
        "Grooved or rounded stones found in sets are often interpreted as bolas weights, though the identification is not always certain.", ""),
    "scraper": ("Scraper", UNDATED, -100000,
        "A stone flake with a steep, sturdy edge for scraping hides and wood.",
        "Cleaning a hide is slow, repetitive work, and a scraper's robust edge survives it. Scrapers are among the most common tools in many stone tool assemblages.",
        "Microscopic wear and residues on scraper edges show what they were used on — hide, wood or plant.", ""),
    "scythe": ("Sickle", UNDATED, -12000,
        "A handle set with a row of small sharp blades, used to cut stems of grass and grain.",
        "Cutting wild cereals by the handful is far quicker with a sickle than by hand, which matters once people start relying on grain.",
        "Stone blades with a distinctive glossy polish — sickle gloss, left by silica in plant stems — are the evidence.",
        "Named 'Scythe' until 2026-09. A scythe is a much later, two-handed tool."),
    "carving_knife": ("Carving Knife", UNDATED, -100000,
        "A small, controllable blade for shaping wood and bone by hand.",
        "Fine control, not force, is what a carving knife is for: whittling a handle, a peg, or a figure.",
        "Knife marks on worked objects, and small blades with suitable wear, are the evidence.", ""),
    "bone_saw": ("Saw-Edged Blade", UNDATED, -30000,
        "A blade with a notched edge, drawn back and forth to cut through bone or antler.",
        "Bone and antler are too hard to slice. Sawing a groove and snapping along it is how they were cut into blanks for needles, points and ornaments.",
        "Saw and groove marks on bone and antler offcuts show how the material was divided.", ""),
    "snares": ("Snare", UNDATED, -30000,
        "A loop of cord set so that an animal pulls it tight around itself.",
        "A snare keeps working while the hunter is elsewhere. Several set at once can feed people with far less effort than a chase.",
        "Snares are made of materials that rot; the evidence is mostly indirect, such as large numbers of small animal bones at a site.", ""),
    "fishing_hook": ("Fish Hook", "≈ 23,000 years ago or earlier", -23000,
        "A curved point that holds a fish once it takes the bait.",
        "A hook lets one person fish from a shore or a boat without nets or traps, and it works in deep water where spears cannot reach.",
        "Hooks carved from shell and bone are among the finds; the oldest examples known come from islands in the western Pacific.", ""),
    "awl": ("Awl", UNDATED, -60000,
        "A sharp point for piercing holes in hide.",
        "Before an eyed needle, clothing was made by punching holes with an awl and pushing cord through them. It is the tool that makes fitted clothing possible.",
        "Pointed bone tools with polish and wear at the tip are the evidence.", ""),
    "fishing_line": ("Fishing Line", UNDATED, -23000,
        "A long cord that joins a hook to the person holding it.",
        "The line is what lets a hook be cast out, sunk deep, and pulled back in.",
        "Lines rarely survive; their use is inferred from hooks, sinkers and the fish bones found with them.", ""),
    "trident": ("Fish Spear", UNDATED, -10000,
        "A spear with several prongs, used to pin fish in shallow water.",
        "Several points spread the strike, so a quick, slippery fish is easier to hold than with a single tip.",
        "Pronged fishing spears are known from wet sites where wood survives; the three-pronged metal trident is much later.",
        "The name 'Trident' suggests a much later metal tool; this entry means any multi-pronged fish spear."),
    "campfire": ("Campfire", UNDATED, -400000,
        "An open fire built on the ground and tended through the night.",
        "A campfire is the social centre of a camp: warmth, light, cooking and a place where people sit together and talk.",
        "Burned bone, heated stones, ash lenses and charcoal in the ground are how archaeologists recognise ancient fires; separating deliberate fires from natural ones is often debated.", ""),
    "hearth": ("Hearth", UNDATED, -300000,
        "A fireplace deliberately built and reused, often ringed with stones.",
        "A hearth is fire given a fixed place. People return to it, organise work around it, and build shelters beside it.",
        "Repeated layers of ash and burned material in the same spot, sometimes with a stone ring, mark a hearth.", ""),
    "charcoal": ("Charcoal", UNDATED, -300000,
        "Wood burned with little air, leaving a light, black fuel that burns hot.",
        "Charcoal burns hotter and cleaner than wood, and it also made one of the first drawing materials.",
        "Charcoal survives very well, and it is also what radiocarbon dating most often measures.", ""),
    "kiln": ("Kiln", UNDATED, -10000,
        "An enclosed fire built to reach and hold high temperatures.",
        "Walling a fire in traps its heat, which is what firing pottery, burning lime and eventually smelting metal require.",
        "Fired clay objects, burned structures and heat-reddened ground reveal kilns and their temperatures.",
        "Clay figurines were fired in some places long before pottery vessels and purpose-built kilns."),
    "flint": ("Flint", UNDATED, -500000,
        "A hard, glassy stone that breaks into very sharp edges.",
        "Flint and similar stones fracture predictably, which made them the preferred raw material for knapping wherever they could be found.",
        "Where a tool's stone came from can often be traced by its chemistry and appearance, which shows people carrying good stone over long distances.", ""),
    "slow_match": ("Smouldering Cord", UNDATED, -30000,
        "A cord that burns slowly, used to keep a flame alive while travelling.",
        "Starting a fire from nothing is hard work. Carrying a smouldering ember is easier, and a slow-burning cord is one way to do it.",
        "Such cords rarely survive; the practice is known mainly from later historical and ethnographic accounts.",
        "Named 'Slow Match' until 2026-09. A slow match in the strict sense is a gunpowder-era fuse."),
    "ash": ("Ash", UNDATED, -400000,
        "The pale, powdery residue left when a fire burns out.",
        "Ash was useful as well as waste: it was spread on floors, mixed into plaster, and used to preserve and clean.",
        "Layers of ash in a site are one of the clearest signs of repeated fire use.", ""),
    "cooked_marrow": ("Cooked Marrow", UNDATED, -300000,
        "The fatty tissue inside large bones, eaten after cracking or heating them.",
        "Marrow is rich in fat, which is hard to come by from lean wild meat. Getting it out was worth the effort.",
        "Bones broken open in a consistent pattern, sometimes burned, show deliberate marrow extraction.", ""),
    "spit": ("Roasting Spit", UNDATED, -100000,
        "A stick used to hold food over a fire.",
        "Holding food over the flames instead of in them cooks it evenly without burning it.",
        "Spits are wooden and rarely survive; the practice is inferred from burned bone and hearth layout.", ""),
    "palisade": ("Palisade", UNDATED, -9000,
        "A fence of upright timbers set closely side by side.",
        "A palisade marks a settlement's edge and protects what is inside it: people, animals and stored food.",
        "Rows of post-holes in the ground outline where palisades once stood.", ""),
    "stone_hut": ("Stone Hut", UNDATED, -12000,
        "A small dwelling with walls or foundations of stone.",
        "Stone walls last for generations. A stone house is a commitment to a place.",
        "Stone foundations are among the most durable remains of early dwellings.", ""),
    "reinforced_shelter": ("Braced Shelter", UNDATED, -30000,
        "A shelter whose frame has been tied and braced to stand up to wind and weight.",
        "Tying the frame together turns a lean-to into a structure that can hold a heavy covering and last a season.",
        "Frames are perishable; post-holes and floor layouts give the shape of what stood there.", ""),
    "bone_tent": ("Bone Dwelling", UNDATED, -20000,
        "A shelter whose frame or weights are made from large animal bones.",
        "Where trees are scarce, big bones can do the work of timber.",
        "Arrangements of large bones in circular patterns, found in cold, treeless regions, are interpreted as dwellings.", ""),
    "smokehouse": ("Smokehouse", UNDATED, -10000,
        "A shelter in which food is hung in smoke to dry and preserve it.",
        "Smoke dries food and slows spoilage. Preserving a large catch means food lasts well beyond the season it was caught in.",
        "Evidence is indirect: structures with heavy smoke deposits and large accumulations of fish or meat bones.", ""),
    "lashing": ("Lashing", UNDATED, -30000,
        "Rope wound tightly around two pieces to hold them together.",
        "Lashing is how frames get built without nails or glue: shelters, rafts, racks and ladders.",
        "Lashings themselves rarely survive; notches and grooves worn into wood show where they sat.", ""),
    "anchor": ("Stone Anchor", UNDATED, -8000,
        "A heavy stone tied to a line to hold a boat or a net in place.",
        "An anchor keeps a boat steady against current and wind while its crew fishes or waits.",
        "Pierced or grooved heavy stones found near shores and wrecks are identified as anchors.", ""),
    "ladder": ("Ladder", UNDATED, -10000,
        "Two rails joined by rungs, for climbing up and down.",
        "A ladder reaches roofs, storage platforms and cliff dwellings that feet alone cannot.",
        "Ladders are known from rock art and from wooden examples preserved in dry or waterlogged sites.", ""),
    "rope": ("Rope", UNDATED, -50000,
        "Several strands of cord twisted together into one strong line.",
        "Twisting strands together multiplies strength. Rope pulls, hauls, lashes, climbs and anchors.",
        "Fragments of twisted fibre, and impressions of cord in clay, are the evidence.", ""),
    "weaving_shuttle": ("Weaving Shuttle", UNDATED, -9000,
        "A tool that carries thread back and forth between the threads of a weave.",
        "A shuttle speeds up weaving, which turns fibre into cloth much faster than knotting or twining by hand.",
        "Weaving tools are known from later sites; how early simple weaving began is uncertain.", ""),
    "tapestry": ("Woven Hanging", UNDATED, -5000,
        "A decorated textile hung on a wall or across a doorway.",
        "A hanging keeps out draughts and marks a space as someone's own, with colour and pattern.",
        "Textiles rarely survive; ancient examples come from very dry or waterlogged places.",
        "Tapestry in the strict sense is a much later craft; this entry stands for decorated hangings in general."),
    "slingshot": ("Sling", UNDATED, -10000,
        "A pouch between two cords, whirled to throw a stone hard and far.",
        "A sling multiplies the speed of a throw. It is light, easy to make, and fires ammunition you can pick up anywhere.",
        "Slings rot; stones shaped as sling ammunition are the usual evidence.",
        "Named 'Slingshot' until 2026-09. A slingshot with an elastic band is a modern object."),
    "mortar": ("Mortar", UNDATED, -20000,
        "A hollowed stone in which things are pounded or ground.",
        "Pounding seeds, nuts and pigments in a mortar makes food and colour that hands alone cannot produce.",
        "Hollowed stones with residues of plants or pigment show what was ground in them.", ""),
    "pestle": ("Pestle", UNDATED, -20000,
        "A heavy, rounded stone held in the hand to pound and grind.",
        "The pestle is the moving half of a grinding pair; it turns hard seeds into flour and paste.",
        "Worn ends and residues of starch on grinding stones reveal what was processed.", ""),
    "wooden_bowl": ("Wooden Bowl", UNDATED, -10000,
        "A container carved or burned out of a single piece of wood.",
        "A bowl holds food and water, and it can be carried. Before pottery, wood, bark and gourds did this job.",
        "Wooden vessels survive only in waterlogged or very dry sites.", ""),
    "dugout_canoe": ("Dugout Canoe", "≈ 10,000 years ago or earlier", -8000,
        "A boat made by hollowing out a single log.",
        "A dugout carries people and loads along rivers, lakes and coasts. It turns water from a barrier into a route.",
        "The oldest surviving dugouts were preserved in peat and mud; older boats almost certainly existed but have not survived.", ""),
    "bone_container": ("Bone Container", UNDATED, -30000,
        "A hollow bone or horn used to hold small things.",
        "Hollow bones make ready-made tubes for pigment, needles or tinder, sealed with a plug.",
        "Hollow bones with residues or wear consistent with use as containers have been found at a number of sites.", ""),
    "lime": ("Lime", UNDATED, -10000,
        "A white powder made by burning limestone or shell, which hardens again when wet.",
        "Lime makes plaster and mortar. It set floors and walls hard, and later bound whole buildings together.",
        "Lime plaster floors are identified by their chemistry and texture, which differ from natural deposits.", ""),
    "bundle": ("Bundle", UNDATED, -30000,
        "Stems or reeds tied tightly together.",
        "A bundle of reeds floats, burns steadily, thatches a roof or builds a boat. Tying weak things together makes a strong one.",
        "Bundles rarely survive; impressions and ethnographic comparison are the main evidence.", ""),
    "trophy_necklace": ("Pendant Necklace", UNDATED, -40000,
        "Teeth, shells or carved pieces strung and worn around the neck.",
        "Ornaments say something about the wearer — who they are, where they belong, what they have done. Wearing them is a form of symbolic communication.",
        "Perforated teeth and shells with string wear around their holes show they were worn.", ""),
    "sauna": ("Sweat Lodge", UNDATED, -5000,
        "A small, closed shelter filled with heat from hot stones.",
        "Steam and heat were used for cleaning, healing and ritual in many cultures around the world.",
        "Structures with heaps of fire-cracked stones are sometimes interpreted as sweat houses, though the identification can be uncertain.",
        "Named 'Sauna' until 2026-09. The Finnish sauna is one late example of a much wider practice."),
    "fence": ("Fence", UNDATED, -9000,
        "A barrier of posts and rails around a plot or an enclosure.",
        "A fence keeps animals in or out and marks land as someone's. It is closely tied to herding and farming.",
        "Post-holes in regular lines show where fences once stood.", ""),
    "engraver": ("Engraver", UNDATED, -40000,
        "A stone tool with a strong, narrow point for cutting grooves.",
        "An engraver cuts lines into bone, antler and stone: marks, patterns, and the first carved images.",
        "Microscopic wear on the tip, and the grooves themselves, identify engraving tools.", ""),
    "flute": ("Flute", "≈ 40,000 years ago", -40000,
        "A hollow bone with finger holes, played by blowing across or into it.",
        "A flute is deliberate, repeatable music. Some of the oldest securely identified musical instruments are flutes carved from bird bone and ivory.",
        "Carved flutes from caves in southwest Germany are among the oldest known instruments.", ""),
    "bullroarer": ("Bullroarer", UNDATED, -20000,
        "A flat piece of wood on a cord, swung in a circle to make a roaring sound.",
        "The bullroarer carries sound over long distances and is used in ceremony in many cultures.",
        "Some carved slats found at old sites are interpreted as bullroarers; the identification is not always certain.", ""),
    "bow_drill": ("Bow Drill", UNDATED, -10000,
        "A bow whose string is wrapped around a spindle, spinning it fast.",
        "Spinning a spindle against wood makes enough friction heat to start a fire. The same trick drills holes in beads and wood.",
        "Drilled beads and wear marks on hearth boards are the evidence for bow drills.", ""),
    "bow": ("Bow", "Possibly ≈ 60,000 years ago or earlier (debated)", -60000,
        "A springy stave and a string, which store the pull of the arm and release it into an arrow.",
        "A bow shoots farther and more accurately than a thrown spear, and lets a hunter strike from hiding.",
        "Bows rarely survive; the case for early archery rests on small stone points with impact damage, which is debated.", ""),
    "atlatl": ("Spear-Thrower", "Upper Palaeolithic", -20000,
        "A handle that holds the back of a dart, extending the arm when throwing.",
        "The spear-thrower works as a lever: it lengthens the arm, so a dart leaves the hand much faster.",
        "Carved spear-throwers of antler and bone are known from Upper Palaeolithic Europe.", ""),
    "boiling_stone": ("Boiling Stones", UNDATED, -30000,
        "Stones heated in a fire and dropped into water to heat it.",
        "Boiling stones heat water in a container that cannot go on a fire: a skin, a basket or a wooden trough. It makes stews, softens plants and renders fat.",
        "Heaps of fire-cracked rock, shattered by sudden cooling, are the evidence.", ""),
    "tallies": ("Tally Marks", UNDATED, -40000,
        "A series of notches cut into bone or wood.",
        "Marks that stand for things counted are a small step towards writing numbers down.",
        "Notched bones are well known; whether a particular set of marks was a count is often debated.", ""),
    "dice": ("Knucklebones", UNDATED, -5000,
        "Small animal ankle bones thrown in games of chance and skill.",
        "Throwing bones to see how they land is one of the oldest games, and was also used in divination.",
        "Collections of ankle bones, some worn or marked, are found at many sites.",
        "Named 'Dice' until 2026-09. Six-sided dice are a later development of the same idea."),
    "sledge": ("Maul", UNDATED, -10000,
        "A heavy hammer on a long handle.",
        "Weight and a long swing split logs, drive stakes and break stone.",
        "Heavy hammer stones with handle wear are the usual evidence.",
        "Named 'Sledge' until 2026-09."),
    "mattock": ("Mattock", UNDATED, -10000,
        "A digging tool with a broad blade on one side of the head.",
        "A mattock breaks and turns heavy ground, which matters for digging roots, ditches and, later, fields.",
        "Heavy blades with digging wear are the typical evidence.", ""),
    "microblade": ("Microblade", UNDATED, -30000,
        "A tiny, very regular stone blade, made in large numbers.",
        "Microblades are small replaceable parts: set in rows along a shaft or handle, they make points, knives and sickles that can be repaired one blade at a time.",
        "Microblades and the cores they were struck from are distinctive and easy to recognise.", ""),
    "handaxe": ("Handaxe", "≈ 1.7 million years ago onward", -1700000,
        "A stone shaped on both faces into a teardrop with a sharp edge all round.",
        "The handaxe was made to a consistent plan for more than a million years. It shows that its makers held a shape in mind before they started.",
        "Handaxes of the Acheulean tradition are found across Africa, Europe and Asia.", ""),
    "shears": ("Paired Blades", UNDATED, -3000,
        "Two blades that cut by closing on each other.",
        "Cutting from both sides at once gives a clean, controlled cut through hair, fibre and cloth.",
        "True shears are made of metal and appear much later; this entry stands for the idea of cutting with two edges.",
        "Named 'Shears' until 2026-09. Metal shears are Iron Age and later."),
    "weir": ("Fish Weir", UNDATED, -8000,
        "A barrier of stones or stakes built across a stream to steer fish into a trap.",
        "A weir harvests fish every day with no one watching. Some systems were built and maintained over many generations.",
        "Lines of stakes and stones in rivers and tidal zones mark ancient weirs.", ""),
    "flail": ("Flail", UNDATED, -5000,
        "Two sticks joined by a short cord, swung to beat grain from its husk.",
        "Threshing separates grain from straw. The flail made this slow task much faster.",
        "Flails are perishable; the practice is known from later depictions and historical records.", ""),
    "wildfire": ("Wildfire", "Older than us", -4000000,
        "Fire that spreads across the land on its own.",
        "Long before people made fire, they met it. Early fire use probably began by taking burning material from natural fires.",
        "Charcoal in ancient lake and ocean sediments records the history of natural fire.", ""),
    "tattoo_needle": ("Tattoo Needle", UNDATED, -5000,
        "A fine point used to put pigment into skin.",
        "Tattoos mark identity, status, healing or belonging, and they cannot be taken off.",
        "Tattooed preserved bodies prove the practice; sharp points with pigment on them are evidence for the tools.", ""),
    "spike_trap": ("Spike Trap", UNDATED, -10000,
        "A pit or passage set with sharpened stakes.",
        "Traps let terrain do the hunting. A well-placed pit on a game trail works without a hunter nearby.",
        "Pit features and sharpened stakes are occasionally preserved; many identifications are uncertain.", ""),
    "moat_wall": ("Ditch and Bank", UNDATED, -7000,
        "A ditch dug around a settlement, with the earth piled up on the inside.",
        "Digging a ditch and piling up a bank marks a boundary, drains the ground and makes the inside harder to reach.",
        "Enclosure ditches show up clearly in excavation and in aerial photographs of crop marks.",
        "Named 'Moat Wall' until 2026-09."),
    "beacon": ("Signal Fire", UNDATED, -10000,
        "A fire lit on high ground to be seen from far away.",
        "Fire and smoke carry a message across a valley faster than a runner can.",
        "Signal fires leave little trace; most evidence comes from historical and ethnographic accounts.",
        "Named 'Beacon' until 2026-09."),
    "tripwire": ("Tripwire", UNDATED, -10000,
        "A cord stretched low across a path, which sets off a trap when touched.",
        "A tripwire lets the animal spring the trap itself, so it can be set and left.",
        "Known mainly from ethnographic practice; the materials rarely survive.", ""),
    "fish_drying_rack": ("Fish Drying Rack", UNDATED, -10000,
        "A frame on which split fish are hung to dry in the sun, wind or smoke.",
        "Dried fish keeps for months. A large seasonal run of fish becomes food for the whole year.",
        "Post-holes near shores, together with large numbers of fish bones, point to drying and storage.", ""),
    "trench": ("Drainage Ditch", UNDATED, -8000,
        "A channel dug to carry water away from a dwelling or field.",
        "Keeping water out of a floor or away from crops makes a place livable and farmable.",
        "Ditches appear in excavation as bands of different soil that filled them in.",
        "Named 'Trench' until 2026-09."),
    "brand": ("Firebrand", UNDATED, -60000,
        "A burning stick taken from a fire.",
        "A firebrand carries fire to a new place, drives off animals, and lights a torch or a new hearth.",
        "Firebrands leave no specific trace; their use is inferred from fire use generally.",
        "Named 'Brand' until 2026-09."),
    "javelin": ("Javelin", UNDATED, -300000,
        "A light spear balanced for throwing rather than thrusting.",
        "A thrown spear reaches an animal before it gets close, which makes hunting safer.",
        "Whether early wooden spears were thrown or thrust is judged from their balance and shape, and remains debated.", ""),
    "pike": ("Long Spear", UNDATED, -300000,
        "A long, heavy spear used for thrusting.",
        "A long thrusting spear keeps a large animal at a distance while the hunter holds his ground.",
        "Preserved wooden spears and wear on stone points help separate thrusting from throwing weapons.",
        "Named 'Pike' until 2026-09."),
    "lumber": ("Split Timber", UNDATED, -10000,
        "Wood split or cut into beams and planks.",
        "Straight, even timber is what frames, boats and furniture are built from.",
        "Tool marks on preserved wood show how it was split and shaped.",
        "Named 'Lumber' until 2026-09."),
    "quarry": ("Quarry", UNDATED, -100000,
        "A place where stone is dug or broken out of the ground.",
        "Good stone is not everywhere. A quarry is a place people returned to again and again to get it.",
        "Quarries leave pits, waste flakes and abandoned blanks in large quantities.", ""),
    "kindling": ("Kindling", UNDATED, -400000,
        "Small, dry, thin pieces of wood and plant that catch fire easily.",
        "A fire is built up in stages; kindling bridges the gap between a spark and a log.",
        "Kindling burns away completely; its use is inferred from fire-making itself.", ""),
    "peg": ("Peg", UNDATED, -10000,
        "A small shaped stick driven into the ground or into wood to hold things in place.",
        "Pegs hold down tents, snares and hides being stretched, and they join wood without nails.",
        "Pegs survive in waterlogged sites, and peg holes are visible in preserved woodwork.", ""),
    "weight": ("Net Sinker", UNDATED, -20000,
        "A small weight tied to the bottom of a net or line to make it sink.",
        "Sinkers hold a net upright in the water, so it catches fish instead of floating on the surface.",
        "Notched or grooved small stones found near water are often identified as sinkers.",
        "Named 'Weight' until 2026-09."),
    "flint_spark": ("Strike-a-Light", UNDATED, -40000,
        "A hard stone struck against a mineral to throw sparks into tinder.",
        "Striking sparks is a fast, portable way to make fire, with no need to carry an ember.",
        "Wear marks on some flint tools have been interpreted as evidence of striking sparks; the interpretation is debated.",
        "Named 'Flint Spark' until 2026-09."),
    "hoe": ("Hoe", UNDATED, -10000,
        "A blade set across a handle for loosening soil and pulling weeds.",
        "A hoe breaks up soil and clears weeds, one of the most basic tasks in tending plants.",
        "Stone and bone blades with soil polish are the evidence.", ""),
    "workshop": ("Work Area", UNDATED, -100000,
        "A place set aside for making things.",
        "Separating work into areas — knapping here, butchering there — shows planning and organised activity.",
        "Clusters of debris from a single activity, such as knapping flakes, mark work areas at a site.",
        "Named 'Workshop' until 2026-09."),
}

# A few non-placeholder Stone Age entries had a wrong date as well.
DATE_FIXES = {
    "hafted_tool": ("≈ 500,000 years ago or earlier (debated)", -500000),
    "retiarius_trap": (UNDATED, -10000),
}
RENAMES = {"retiarius_trap": "Weighted Net"}


def main() -> None:
    arr = json.loads(FILE.read_text(encoding="utf-8"))
    by_id = {n["id"]: n for n in arr}
    missing = [k for k in E if k not in by_id]
    if missing:
        raise SystemExit(f"unknown ids: {missing}")
    for nid, (name, date, ds, l1, l2, l3, extra) in E.items():
        n = by_id[nid]
        n["n"] = name
        n["date"] = date
        n["ds"] = ds
        n["l1"], n["l2"], n["l3"] = l1, l2, l3
        n["ev"] = "Not yet sourced"
        n["src"] = ["source_required"]
        n["caution"] = (extra + " " + GAMEPLAY).strip() if extra else GAMEPLAY
        if n.get("tags") == ["crafted"]:
            n["tags"] = ["stone age", "crafted"]
    for nid, (date, ds) in DATE_FIXES.items():
        by_id[nid]["date"], by_id[nid]["ds"] = date, ds
    for nid, name in RENAMES.items():
        by_id[nid]["n"] = name
    FILE.write_text(json.dumps(arr, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"rewrote {len(E)} entries")


if __name__ == "__main__":
    main()
