'use client';

import { useState, useSyncExternalStore, type CSSProperties } from 'react';
import { ARCHIVE_STORES, archiveSections, type ModeArchiveRecord } from '@/lib/museum/archive';
import type { ProvenanceKind } from '@/lib/museum/types';

/* ============================================================================
   RECORDS — the Mode Archive wing. Reports, preserved settlements, decoded
   tablets, expedition records and field reports that the player's runs of the
   extra modes produced. Shelved like an archive, pulled out one drawer at a
   time — deliberately unlike the Humanity galleries, because these are the
   player's records, not humanity's history. Each keeps its provenance label.
   ========================================================================== */

const KIND_LABEL: Record<ProvenanceKind, string> = {
  'historical-fact': 'Historical fact',
  'reference-reconstruction': 'Reconstruction',
  'procedural-fictional': 'Generated record',
  'speculative': 'Speculative',
};

const dateFmt = new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric' });

function useArchiveVersion(): number {
  const vs = ARCHIVE_STORES.map(s =>
    // eslint-disable-next-line react-hooks/rules-of-hooks -- fixed-length list, stable order
    useSyncExternalStore(s.subscribe, s.getVersion, () => 0));
  return vs.reduce((a, b) => a + b, 0);
}

export function ModeArchiveWing() {
  useArchiveVersion();
  const sections = archiveSections();
  const [open, setOpen] = useState<string | null>(null);
  const filled = sections.filter(s => s.records.length > 0);
  const total = filled.reduce((n, s) => n + s.records.length, 0);

  return (
    <div className="ra">
      <header className="ra-head">
        <p className="mono ra-eyebrow">Mode Archives</p>
        <h2 className="ra-title">Records</h2>
        <p className="ra-sub">
          What your runs of the other modes produced — expedition records, settlements, excavation reports,
          translated tablets, episode records, field reports and dependency maps. These are your records, generated
          by play, and are kept out of humanity&rsquo;s galleries.
        </p>
        <p className="mono ra-count">{total} {total === 1 ? 'record' : 'records'} filed</p>
      </header>

      {filled.length === 0 && (
        <p className="ra-empty">
          The shelves are empty. Finish a run of Survival, Civilization, Archaeologist, Decipher, Historical Escape Room,
          Alien Archaeology or Reverse Evolution from the Mode Hub, and its record is filed here.
        </p>
      )}

      <div className="ra-shelves">
        {filled.map(s => (
          <section key={s.id} className="ra-shelf" style={{ ['--acc' as string]: s.accent } as CSSProperties} aria-label={s.label}>
            <header className="ra-shelf-head">
              <h3>{s.label}</h3>
              <p>{s.blurb}</p>
              <span className="mono">{s.records.length}</span>
            </header>
            <div className="ra-drawers">
              {s.records.map((r: ModeArchiveRecord) => {
                const isOpen = open === r.id;
                return (
                  <article key={r.id} className={'ra-drawer' + (isOpen ? ' open' : '')}>
                    <button type="button" className="ra-drawer-face" aria-expanded={isOpen} onClick={() => setOpen(isOpen ? null : r.id)}>
                      <span className="mono ra-kind">{KIND_LABEL[r.provenance.kind]}</span>
                      <span className="ra-name">{r.title}</span>
                      <span className="mono ra-date">{r.createdAt ? dateFmt.format(r.createdAt) : ''}</span>
                    </button>
                    {isOpen && (
                      <div className="ra-drawer-body">
                        {r.provenance.note && <p>{r.provenance.note}</p>}
                        {r.tags && r.tags.length > 0 && <p className="mono ra-tags">{r.tags.join(' · ')}</p>}
                        {r.provenance.seed !== undefined && <p className="mono ra-seed">Seed {String(r.provenance.seed)}</p>}
                        <p className="ra-prov">
                          {r.provenance.kind === 'procedural-fictional'
                            ? 'Generated by your run — a record of play, not of real history.'
                            : r.provenance.kind === 'speculative'
                              ? 'One interpretation the evidence in your run did not fully confirm.'
                              : 'A labelled reconstruction.'}
                        </p>
                      </div>
                    )}
                  </article>
                );
              })}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
